# Generated by Django 5.0.1 on 2024-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
